#### 1. Import NumPy

Make sure to follow the conventions!

In [3]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Expected output

#### 3. Create an array of 10 ones

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Expected output

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [37]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Expected output

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create a vector, named `arr`, of 10 zeros the fifth value of which is 1.

In [3]:
arr = np.zeros(10)
arr[4] = 1

In [4]:
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create an array of the integers from 10 to 50

In [5]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# Expected output

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 7. Reverse an array in **TWO** ways: using 'the Python way' and using a NumPy function

In [28]:
arr = np.array([1, 2, 3])

print(np.flip(arr))

normal_array = [1, 2, 3]
reversed_array = normal_array[::-1]
print(reversed_array)

[3 2 1]
[3, 2, 1]


In [ ]:
# Expected output

Using the Python way: [3 2 1]
Using a NumPy function: [3 2 1]


#### 8. Create a 5x5 array with 1 on the border and 0 inside

In [44]:
matrix = np.zeros((5,5))

matrix[[0,-1], :] = 1.0
matrix[:, [0,-1]] = 1.0

print(matrix)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Expected output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 9. Add a border filled with 0's on the two sides of an array.

> Hint: [np.pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)

In [6]:
arr = np.array([1, 2, 3])

np.pad(arr, (1,), 'constant', constant_values=0)

array([0, 1, 2, 3, 0])

In [ ]:
# Expected output

array([0, 1, 2, 3, 0])

#### 10. Create an array of all the even integers from 10 to 50

In [10]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# Expected output

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 11. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Expected output

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 12. Create a 3x3 identity matrix

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Expected output

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 13. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

> Hint: [np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

In [20]:
np.diag([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# Expected output

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 14. Use NumPy to generate a random number between 0 and 1

**Note**: Your result's value should be different from the one shown below.

In [22]:
np.random.rand()

0.19152524209967703

In [ ]:
# Expected output

array([0.65248055])

#### 15. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

**Note**: Your result's values should be different from the ones shown below.

In [11]:
np.random.normal(size=25)

array([-0.70397348, -2.22227113,  0.67181153, -0.83752125,  0.09490853,
        0.52827081,  1.04339413,  0.81738702, -0.50067256,  1.03207868,
       -0.34580706, -0.74044173, -1.44941747, -1.28757433,  1.01071092,
       -1.22808857, -0.26833929, -0.73486495,  0.02842985, -0.44952273,
        1.54772717, -0.65726713, -0.45385535, -1.94886805,  0.37324908])

In [ ]:
# Expected output

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 16. Create a 3x3x3 array with random values drawn from the uniform distribution

**Note**: Your result's values should be different from the ones shown below.


In [13]:
np.random.uniform(size=(3,3,3))

array([[[0.10200487, 0.57266685, 0.78939989],
        [0.78995274, 0.26510918, 0.23180286],
        [0.31063465, 0.57732402, 0.10147827]],

       [[0.87736055, 0.36600471, 0.89261256],
        [0.80582859, 0.11566096, 0.62320391],
        [0.12455257, 0.72604413, 0.98431886]],

       [[0.85401316, 0.98365154, 0.5233174 ],
        [0.90062497, 0.1779721 , 0.87878985],
        [0.5458934 , 0.90186121, 0.94775574]]])

In [ ]:
# Expected output

array([[[0.93641099, 0.2920839 , 0.02292815],
        [0.00336922, 0.86947306, 0.68416644],
        [0.8901026 , 0.3837379 , 0.28653589]],

       [[0.10726099, 0.43744832, 0.00470833],
        [0.29069139, 0.64529908, 0.85020447],
        [0.51284435, 0.41215324, 0.19622211]],

       [[0.43004522, 0.92649706, 0.09472069],
        [0.76510854, 0.49565729, 0.56232861],
        [0.07813665, 0.49086324, 0.45172232]]])

#### 17. Create a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values.

**Note**: Your result's values should be different from the ones shown below.

In [14]:
np_uf_array = np.random.uniform(size=(10, 10))
print(np_uf_array)
print(f'Its min value: {np_uf_array.min()}')
print(f'Its max value: {np_uf_array.max()}')


[[0.3289299  0.027415   0.60375733 0.68500165 0.45415982 0.01823841
  0.46579313 0.00362159 0.79329345 0.98063755]
 [0.55787539 0.14980942 0.23523522 0.42733334 0.38420824 0.86534443
  0.07769614 0.06025803 0.86970389 0.20435852]
 [0.90070309 0.07960063 0.12536002 0.79104457 0.81029296 0.41492941
  0.44945324 0.49850946 0.35142922 0.42074658]
 [0.87768246 0.15650237 0.12167149 0.71512465 0.89294985 0.32789527
  0.15535753 0.39111854 0.91372597 0.82524966]
 [0.3628398  0.69334313 0.82637861 0.78065665 0.00413354 0.18236166
  0.18854444 0.89950684 0.87834426 0.40770341]
 [0.80619274 0.15707722 0.71447834 0.74158212 0.45312988 0.52483233
  0.66922512 0.57859608 0.46395975 0.43251882]
 [0.23001278 0.0119136  0.86812176 0.23074307 0.21898325 0.85221908
  0.41996045 0.89625219 0.3902689  0.62921159]
 [0.22901147 0.94302182 0.39859786 0.72733707 0.6661251  0.3284235
  0.72912924 0.77928266 0.28616268 0.59980088]
 [0.07464087 0.39902645 0.51926616 0.65639504 0.78225829 0.20974387
  0.3662685  

In [ ]:
# Expected output

The array: [[0.19932859 0.92905065 0.55492647 0.09878608 0.0421074  0.74219358
  0.92844055 0.62528946 0.35357668 0.88013918]
 [0.36971412 0.74932736 0.02445995 0.72873717 0.48864481 0.14421664
  0.56846658 0.40363749 0.3233466  0.95147426]
 [0.98339368 0.39612436 0.03609193 0.10611245 0.1410213  0.21099682
  0.3285783  0.39140252 0.88863881 0.81498748]
 [0.25423077 0.0756975  0.77587885 0.29315387 0.56795003 0.90145549
  0.95278316 0.63800115 0.14696466 0.08528442]
 [0.08048731 0.55554534 0.21157669 0.37491896 0.95567126 0.72478012
  0.64849367 0.05571253 0.12339177 0.95575902]
 [0.90842177 0.74316806 0.61710506 0.05885491 0.88051201 0.86814746
  0.26131788 0.89392307 0.45475956 0.26810516]
 [0.79185601 0.19973093 0.10674687 0.9080987  0.50335231 0.17405093
  0.39030326 0.48112173 0.74450033 0.76288692]
 [0.68992283 0.52305591 0.94364282 0.623963   0.04065964 0.23544532
  0.38685327 0.9687442  0.529897   0.37273771]
 [0.88262217 0.90518014 0.24570464 0.49601259 0.23893452 0.53227759
 

#### 18. Create a random array with values drawn from the uniform distribution of size 30 and find the mean value

In [18]:
np_arr = np.random.uniform(size=30)
print(f'The array: {np_arr}')
print(f'Its mean: {np.mean(np_arr)}')

The array: [0.64137463 0.20643795 0.49368774 0.97729241 0.92012519 0.68749679
 0.93161153 0.71846557 0.06375609 0.73763737 0.3138554  0.72677651
 0.19403243 0.49260734 0.32437412 0.41980408 0.47827019 0.26001372
 0.90543722 0.24159073 0.04824951 0.59282389 0.58139667 0.09970427
 0.11114699 0.66987117 0.25359918 0.0866986  0.49313533 0.37933248]
Its mean: 0.46835350313299673


In [ ]:
# Expected output

The array: [0.65580703 0.66012918 0.44607318 0.08230611 0.03965247 0.98197551
 0.07286258 0.08288793 0.5283879  0.26948948 0.29579988 0.44204416
 0.42570657 0.74707057 0.96866384 0.96437312 0.38116077 0.74621085
 0.26497925 0.33115365 0.963408   0.05087827 0.36557266 0.66121816
 0.24851936 0.25971588 0.40104167 0.90926914 0.80488701 0.31365462]
Its mean: 0.4788299599451823


#### 19. Create the following matrix:

In [25]:
np.arange(0.01, 1.01, 0.01).reshape((10, 10))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# Expected output

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 20. Create an array of 20 linearly spaced points between 0 and 1:

In [29]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# Expected output

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs.

In all of the solutions until the last task before the section `NumPy Operations` you should be using `mat`.

In [30]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 21. Write code that reproduces the output shown below.

In [34]:
# CODE HERE
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Expected output

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 22. Write code that reproduces the output shown below.

In [37]:
mat[3, 4]

np.int64(20)

In [ ]:
# Expected output

20

#### 23. Write code that reproduces the output shown below.

In [41]:
[[elem] for elem in mat[:3, 1]]

[[np.int64(2)], [np.int64(7)], [np.int64(12)]]

In [ ]:
# Expected output

array([[ 2],
       [ 7],
       [12]])

#### 24. Write code that reproduces the output shown below.

In [43]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
# Expected output

array([21, 22, 23, 24, 25])

#### 25. Write code that reproduces the output shown below.

In [45]:
mat[[3,4], :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Expected output

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 26. Find the indices of the non-zero elements in the provided array.

In [54]:
arr = np.array([1,2,0,0,4,0])

np.nonzero(arr)

# Your code here

(array([0, 1, 4]),)

In [ ]:
# Expected output

array([0, 1, 4])

## NumPy Operations

#### 27. Get the sum of all the values in mat

In [55]:
np.sum(mat)

np.int64(325)

In [ ]:
# Expected output

325

#### 28. Get the standard deviation of the values in mat

In [56]:
np.std(mat)

np.float64(7.211102550927978)

In [ ]:
# Expected output

7.211102550927978

#### 29. Get the sum of all the columns in mat

In [61]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# Expected output

array([55, 60, 65, 70, 75])

#### 30. Create and multiply a 5x3 matrix by a 3x2 matrix (matrix product). The matrices can hold random values or you can create them manually.

**Note**: In this example output the matrices held random values, so your result's values should be different from the ones shown below.

In [71]:
np_arr_one = np.random.rand(15).reshape((5, 3))

np_arr_two = np.random.rand(6).reshape((3,2))

np.matmul(np_arr_one, np_arr_two)


array([[0.4679375 , 0.91602488],
       [1.15416681, 1.76055888],
       [1.25996208, 2.04177896],
       [0.87486987, 1.379602  ],
       [0.83728712, 1.45673376]])

In [ ]:
# Expected output

array([[0.92284566, 0.4834381 ],
       [1.36591969, 0.86692985],
       [0.92732258, 0.57791729],
       [1.20870496, 0.66362074],
       [1.48551291, 0.86352205]])

#### 31. Create a 1D array of random integers between 0 and 9. Negate all elements which are between 3 and 8.

In [75]:
list_rands = np.random.randint(0, 10, 10)

[-el if el >= 3 and el <=8 else el for el in list_rands]

[np.int32(9),
 np.int32(2),
 np.int32(-3),
 np.int32(0),
 np.int32(-7),
 np.int32(-4),
 np.int32(-7),
 np.int32(-4),
 np.int32(-8),
 np.int32(-7)]

In [ ]:
# Expected output

array([ 4,  2,  5, -7, -2,  0, -3, -6, -8,  4])

#### 32. Create a random array of size 10 and sort it

In [79]:
res = np.random.rand(10)

np.sort(res)

array([0.23251896, 0.29621094, 0.33537703, 0.41249461, 0.50591288,
       0.51854151, 0.62869722, 0.63631737, 0.70336739, 0.7665683 ])

In [ ]:
# Expected output

array([0.21557229, 0.29775351, 0.31513898, 0.48094387, 0.56395818,
       0.61094507, 0.65782361, 0.73666887, 0.74573749, 0.97557176])

#### 33. Create random vector of values drawn from the uniform distribution of size 10 and replace the maximum value by 0

In [93]:
vector = np.random.uniform(0, 1, 10)

print(f'The array: {vector}')
vector[np.argmax(vector)] = 0
print(f'Result: {vector}')

The array: [0.80133508 0.82043505 0.37592832 0.29716328 0.64030887 0.66089375
 0.12301393 0.78954029 0.99363693 0.03010474]
Result: [0.80133508 0.82043505 0.37592832 0.29716328 0.64030887 0.66089375
 0.12301393 0.78954029 0.         0.03010474]


In [ ]:
# Expected output

The array: [0.79753115 0.51085823 0.86710259 0.25025854 0.39803838 0.65002613
 0.89686752 0.1562022  0.76741728 0.62775096]
Result: [0.79753115 0.51085823 0.86710259 0.25025854 0.39803838 0.65002613
 0.         0.1562022  0.76741728 0.62775096]


#### 34. What function can we use to ensure that we always get the same random numbers?

> **Your answer**: seed()